s=set()
s.add(int(input(("enter any number1:\t"))))
s.add(int(input(("enter any number2:\t"))))
s.add(int(input(("enter any number3:\t"))))
s.add(int(input(("enter any number4:\t"))))
s.add(int(input(("enter any number5:\t"))))
s.add(int(input(("enter any number6:\t"))))
s.add(int(input(("enter any number7:\t"))))
s.add(int(input(("enter any number8:\t"))))
print(s)
